services:

  db:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: ./image_api
      dockerfile: Dockerfile.base
    restart: always
    container_name: web
    command: [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]
    working_dir: /app/image_api
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=image_api.settings
      - PYTHONPATH=/app
    depends_on:
      rabbitmq:
        condition: service_started
      db:
        condition: service_healthy

  users:
    tty: true
    build:
      context: ./apps/users
      dockerfile: Dockerfile
    container_name: users
    command: [ "python", "manage.py", "runserver", "0.0.0.0:8001" ]
    working_dir: /app/apps/users
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=image_api.settings
      - PYTHONPATH=/app
    depends_on:
      db:
        condition: service_healthy

  image_service:
    tty: true
    build:
      context: ./apps/image_service
      dockerfile: Dockerfile
    container_name: image_service
    command: [ "python", "manage.py", "runserver", "0.0.0.0:8002" ]
    working_dir: /app/apps/image_service
    volumes:
      - .:/app
    ports:
      - "8002:8002"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=image_api.settings
      - PYTHONPATH=/app
    depends_on:
      db:
        condition: service_healthy

  image_service_tests:
    build:
      context: ./apps/image_service
      dockerfile: Dockerfile
    container_name: image_service_tests
    command: [ "python", "image_api/manage.py", "test", "apps.image_service.tests" ]
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=image_api.settings
      - PYTHONPATH=/app
    depends_on:
      db:
        condition: service_healthy


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  image_event_listener:
    build:
      context: .
      dockerfile: ./apps/image_service/services/rabbitMQ_handlers/Dockerfile
    container_name: image_event_listener
    command: [ "python", "image_event_listener.py" ]
    depends_on:
      rabbitmq:
        condition: service_started
    environment:
      - DJANGO_SETTINGS_MODULE=image_api.settings


volumes:
  postgres_data:
