# apps/image_service/dockerfile
FROM python:3.12.1-slim-bullseye

COPY ../../requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt

COPY ../../ /app/

CMD ["python", "manage.py", "runserver", "0.0.0.0:8002"]
